frontend:
  replicas: 2
  image:
    repository: sumeetp111/devops-ecommerce-frontend
    tag: latest

productService:
  replicas: 1
  image:
    repository: sumeetp111/devops-ecommerce-product-service
    tag: v5

postgres:
  replicas: 1

  image:
    repository: postgres
    tag: "16"

  resources:
    requests:
      cpu: "250m"
      memory: "256Mi"

    limits:
      cpu: "500m"
      memory: "512Mi"

  storage:
    storageClassName: ecommerce-storage
    size: "2Gi" 

  databases:
    host: postgres
    port: "5432"
    name: ecommerce_db

  credentials:
    username: ecommerce_app
    password: devops123

redis:
  replicas: 1

  image:
    repository: redis
    tag: "7"

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"

    limits:
      cpu: "250m"
      memory: "256Mi"

kafka:
  replicas: 1

  image:
    repository: apache/kafka
    tag: "3.9.0"

  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"

    limits:
      cpu: "500m"
      memory: "1Gi"

  ports:
    internal: 9094
    external: 9092
    controller: 9093