services:

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ecommerce-network

  product-service:
    image: devops-ecommerce-product-service:v1
    container_name: product-service
    ports:
      - "8000:8000"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health', timeout=5)"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ecommerce-network

  frontend:
    build:
      context: ./services/frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      PRODUCT_SERVICE_URL: http://product-service:8000
    depends_on:
      product-service:
        condition: service_healthy
    networks:
      - ecommerce-network

volumes:
  postgres-data:
    external: true

networks:
  ecommerce-network:
    driver: bridge