apiVersion: v1
kind: Secret

metadata:
  name: product-db-secret
  namespace: ecommerce

type: Opaque

stringData:
  DB_USER: {{ .Values.postgres.credentials.username | quote }}
  DB_PASSWORD: {{ .Values.postgres.credentials.password | quote }}