apiVersion: apps/v1
kind: Deployment

metadata:
  name: redis
  namespace: ecommerce

spec:
  replicas: {{ .Values.redis.replicas }}

  selector:
    matchLabels:
      app: redis

  template:
    metadata:
      labels:
        app: redis

    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 6379

          resources:
            requests:
              cpu: {{ .Values.redis.resources.requests.cpu | quote }}
              memory: {{ .Values.redis.resources.requests.memory | quote }}

            limits:
              cpu: {{ .Values.redis.resources.limits.cpu | quote }}
              memory: {{ .Values.redis.resources.limits.memory | quote }}